### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by aloshyn** [aloshyn/homepage#4]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by ArMANIAK** [comment]
<section>
  <h3>Languages</h3>
  <p class="tags small"><a href="/uk-ua" hreflang="uk" rel="alternate" class="language" lang="uk">&#x1f1fa;&#x1f1e6; <span>УКРАЇНСЬКА</span></a> <a href="/ru-ru" hreflang="ru" rel="alternate" class="language" lang="ru">&#x1f1f7;&#x1f1fa; <span>РУССКИЙ</span></a> <span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span></p>
</section>
<section>
  <h3>Skills</h3>
  <p class="tags small">HTML CSS JS PHP BOOTSTRAP CorelDRAW <span class="nowrap">MICROSOFT OFFICE</span> PHOTOSHOP WINDOWS </p>
</section>
<section>
  <h3>Likes&#x1f603;</h3>
  <p class="tags small">HUMOUR FIRST AID PATIENCE CATS MOVIES SELF-EDUCATION <span class="nowrap">ATTENTION TO DETAILS</span><em>(It's a lie - sometimes I can't see a thing)</em></p>
</section>
