### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by aloshyn** [aloshyn/homepage#5]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by ArMANIAK** [comment]
<ul class="timeline">
  <li>
    <p><em>3<sup>rd</sup> May 1984</em></p>
    <p><strong>Was born</strong> in <strong>Zhdanov</strong></p>
  </li>
  <li>
    <p><em>3<sup>rd</sup> May 2014</em></p>
    <p><strong>has grown up</strong> in <strong>Mariupol</strong></p>
  </li>
  <li>
    <p>not the nearest future</p>
    <p><strong>Died...</strong> well, actually not yet</p>
  </li>
</ul>
