### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by aloshyn** [aloshyn/homepage#7]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by ArMANIAK** [comment]
<h2>Résumé</h2>
<p>&mdash; Hello! I’m a junior frontend developer<strong style="margin-left: 0.0625em;">*</strong> with 1 years of experience in learning frontend, UI/UX design, application development, and database modeling. I strive to craft at least something that works</p>
<p style="opacity: 0.75;"><strong style="margin-right: 0.0625em;">*</strong>I feel like it's 80-20 by <a href="https://css-tricks.com/the-great-divide/" rel="external">The Great Divide</a> into JavaScript engineer and UX engineer</p>
